[package]
name = "ldk-tutorial-node"
version = "0.1.0"
authors = ["Valentine Wallace <vwallace@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# lightning = { version = "0.0.14", git = "https://github.com/rust-bitcoin/rust-lightning" }
# lightning-block-sync = { version = "0.0.14", git = "https://github.com/rust-bitcoin/rust-lightning", features = [ "rpc-client" ] }
# lightning-invoice = { version = "0.5", git = "https://github.com/rust-bitcoin/rust-lightning" }
# lightning-net-tokio = { version = "0.0.14", git = "https://github.com/rust-bitcoin/rust-lightning" }
# lightning-persister = { version = "0.0.14", git = "https://github.com/rust-bitcoin/rust-lightning" }
# lightning-background-processor = { version = "0.0.14", git = "https://github.com/rust-bitcoin/rust-lightning" }
# lightning = { path = "../rust-lightning/lightning" }
# lightning-block-sync = { path = "../rust-lightning/lightning-block-sync", features = [ "rpc-client" ] }
# lightning-invoice = { path = "../rust-lightning/lightning-invoice" }
# lightning-net-tokio = { path = "../rust-lightning/lightning-net-tokio" }
# lightning-persister = { path = "../rust-lightning/lightning-persister" }
# lightning-background-processor = { path = "../rust-lightning/lightning-background-processor" }
lightning = { path = "../../rust-lightning/lightning" }
lightning-block-sync = { path = "../../rust-lightning/lightning-block-sync", features = [ "rpc-client" ] }
lightning-invoice = { path = "../../rust-lightning/lightning-invoice" }
lightning-net-tokio = { path = "../../rust-lightning/lightning-net-tokio" }
lightning-persister = { path = "../../rust-lightning/lightning-persister" }
lightning-background-processor = { path = "../../rust-lightning/lightning-background-processor" }

base64 = "0.13.0"
bitcoin = "0.26"
bitcoin-bech32 = "0.7"
bech32 = "0.7"
hex = "0.3"

futures = "0.3"
time = "0.2"
rand = "0.4"
serde_json = { version = "1.0" }
tokio = { version = "1.5", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
